<?php

/**
 * ACL
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ACL extends BaseACL
{
    /*
     * ACL::has_permission()
     * @params $am_object_id integer ACLMap's object_id
     * @params $object string ACL's object
     * @params $am_object_type string ACLMap's object_type
     * @params $type string ACL's type
     * @return boolean
     *
     * <code>
     *  $has_permission = ACLMap::has_permission($userid, 'order/new', 'User', 'action')
     * </code>
     *
     * check if the user, group or role has the permission or not
     */
    static public function has_permission($am_object_id, $object, $am_object_type='User', $type="action") {
        $has_permission = false;
        $rs = Doctrine_Query::create()
                            ->select('*')
                            ->from('ACLMap am, ACL a')
                            ->where('am.object_id = ?
                                    AND am.object_type = ?
                                    AND a.object= ?
                                    AND a.object_type= ?
                                    AND am.acl_id = a.id',
                                    array($am_object_id, $am_object_type, $object, $type))
                            ->fetchOne();

        if(!$rs) {
            return null;
        }

        if($rs->permission >= 1) {
            $has_permission = true;
        } else if($rs->permission > -10000){
            $has_permission = $rs->permission;
        }

        return $has_permission;
    }
}