<?php

/**
 * ACLMapTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ACLMapTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ACLMapTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ACLMap');
    }
}