<?php

/**
 * ACLTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ACLTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ACLTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ACL');
    }
}