<?php

/**
 * Role
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Role extends BaseRole
{

    /*
     * 根据用户的角色别名获取用户
     */
    static public function get_users_by_alias($role_alias) {
        return Doctrine_Query::create()
                               ->select('ur.*, r.*, u.*')
                               ->from('User u')
                               ->innerJoin('u.UserRole r')
                               ->leftJoin('u.Role ur')
                               ->where('ur.alias = ?',$role_alias)
                               ->fetchArray();
    }

    static public function get_by_alias($alias) {
        return Doctrine_Query::create()
                               ->select('*')
                               ->from('Role r')
                               ->where('r.alias = ?', $alias)
                               ->fetchOne();
    }

}