<?php

/**
 * UserRoleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserRoleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserRoleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserRole');
    }
}