<?php

/**
 * CommunicationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommunicationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CommunicationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Communication');
    }
}