<?php

/**
 * OrderPeripheralTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrderPeripheralTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrderPeripheralTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrderPeripheral');
    }
}