<?php

/**
 * Payment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Payment extends BasePayment
{
    /*
     * 付款项目状态
     * #是否已到账 0未付款， 1已付款， -1驳回， 2已确认付款
     */

    static public function get_by_id($payment_id) {
        $payment_id = abs(intval($payment_id));
        return Doctrine_Query::create()
                              ->select('*')
                              ->from('Payment p')
                              ->where('p.id = ?', $payment_id)
                              ->fetchOne();
    }

    /*
     * 根据订单的ID和支付款项的状态获取
     */
    static public function get_by_order_and_state($order_id, $state, $type) {
        $order_id = abs(intval($order_id));
        return Doctrine_Query::create()
                               ->select('*')
                               ->from('Payment p')
                               ->where('p.order_id = ? AND is_payed = ? AND type = ?',
                                                    array($order_id, $state, $type))
                               ->fetchOne();
    }


}