<?php

/**
 * SolutionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SolutionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SolutionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Solution');
    }
}