<?php

/**
 * Solution
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Solution extends BaseSolution
{
    static public function get_by_id($id) {
        return Doctrine_Query::create()
                               ->select('*')
                               ->from('Solution s')
                               ->where('s.id = ?', $id)
                               ->fetchOne();
    }

    static public function get_by_order($order_id) {
        return Doctrine_Query::create()
                               ->select('*')
                               ->from('Solution s')
                               ->where('s.order_id = ?', $order_id)
                               ->fetchArray();
    }

    /*
     * Solution::set_unchecked()
     * @params integer $order_id
     *
     * 将订单所有的方案设为未选定
     */
    static public function set_unchecked($order_id) {
        return Doctrine_Query::create()
                               ->update('Solution s')
                               ->set('s.state', '0')
                               ->where('s.order_id = ?', $order_id)
                               ->execute();
    }

    /*
     * 获取当前订单选定的方案
     */
    static public function get_checked($order_id) {
        return Doctrine_Query::create()
                               ->select('*')
                               ->from('Solution s')
                               ->where('s.order_id = ? AND s.state=1', $order_id)
                               ->fetchOne();
    }

    /*
     * 选择某方案
     */
    static public function select($solution_id) {
        $solution = self::get_by_id($solution_id);
        $solution->state = 1;
        $solution->save();
    }

}