<?php

/**
 * Article
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Article extends BaseArticle
{

    static public function get_by_category($id_or_alias, $orderby = 'id DESC') {
        
        $field = is_int($id_or_alias) ? 'id' : 'alias';

        $query = Doctrine_Query::create()
                                ->select('a.*, ac.*, aa.id, aa.username')
                                ->from('Article a')
                                ->leftJoin('a.Category ac')
                                ->leftJoin('a.Author aa');
        if($field == 'id') {
            $query->where('ac.id = ?', $id_or_alias);
        } else {
            $query->where('ac.alias = ?', $id_or_alias);
        }
        $query->orderBy('a.'.$orderby);

        return $query->fetchArray();
    }

   
}