<?php

/**
 * Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Category extends BaseCategory
{
    static public function get_all(){
        return Doctrine_Query::create()
                               ->select('*')
                               ->from('Category c')
                               ->fetchArray();
    }

    static public function get_select($userinfo) {
        
        
        $query = Doctrine_Query::create()
                               ->select('*')
                               ->from('Category c')
                               ->where('c.manager like "%,'.$userinfo['role']['id'].',%"');
        foreach($userinfo['role'] as $role) {
            $query->orWhere('c.manager like "%,'.$role['id'].',%"');
        }
        $categories = $query->fetchArray();
        if(!$categories) {
            return array();
        }
        $cats = array();
        foreach($categories as $k=>$v) {
            $cats[$v['id']] = $v['name'];
        }

        return $cats;
    }

    static public function has_role($catid, $userinfo) {
        $category = CategoryTable::getInstance()->find($catid);
        foreach($userinfo['role'] as $role) {
            $roles[] = $role['id'];
        }

        $cat_roles = array_filter(explode(',', $category->manager));

        foreach($cat_roles as $r) {
            if(in_array($r, $roles)) {
                return $category;
            }
        }

        return false;
    }

}