<?php

/**
 * OrderWorkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrderWorkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrderWorkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrderWork');
    }
}