<?php

/**
 * FormsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FormsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Forms');
    }
}