<?php

/**
 * Forms
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Forms extends BaseForms
{
    static public function get_by_type_and_user($type, $user_id = null) {
        $states = array(
            '正在审核', '已经批准', '<span style="color:red">已拒绝</span>'
        );
        $query = Doctrine_Query::create()
                                ->select('f.*, fu.username')
                                ->from('Forms f')
                                ->leftJoin('f.Owner fu')
                                ->where('type = ?', $type);
        if($user_id) {
            $query->addWhere('fu.id = ?', $user_id);
        }

        $query = $query->addOrderBy('f.id DESC')->fetchArray();

        if(!count($query)) {
            return array();
        }
        
        foreach($query as $k => $v) {
            if($v['form_data']) {
                $query[$k]['form_data'] = @unserialize($v['form_data']);
            }
            $query[$k]['state'] = $states[$v['state']];
            $query[$k]['Owner'] = $v['Owner'][0];
        }

        return $query;

    }

}